name: make check

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  check-ubuntu:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        include:
          - static_linking: true
          - static_linking: false
    steps:
    - name: install dependencies
      run: |
          sudo apt update
          sudo apt install automake autoconf libtool libtool-bin libltdl-dev libltdl7
          sudo apt install libxml2 libxml2-dev libxslt1.1 libxslt1-dev
          sudo apt install libssl1.0.0 libssl-dev libnspr4 libnspr4-dev libnss3 libnss3-dev libnss3-tools libgcrypt20 libgcrypt20-dev libgnutls28-dev
    - uses: actions/checkout@v2
    - run: mkdir build
    - name: configure
      working-directory: build
      run: ../autogen.sh --enable-werror --enable-static-linking=${{ matrix.static_linking }}
    - name: make
      working-directory: build
      run: make
    - name: make check
      working-directory: build
      run: make check
  
  check-osx:
    runs-on: macos-latest
    strategy:
      fail-fast: false
      matrix:
        include:
          - static_linking: true
          - static_linking: false
    steps:
    - name: install dependencies
      # nss is disabled for now          
      run: |
          brew update
          brew install automake autoconf libtool
          brew install libxml2 libxslt
          brew install openssl libgcrypt gnutls        
    - uses: actions/checkout@v2
    - run: mkdir build
    - name: configure
      working-directory: build
      run: ../autogen.sh --enable-werror --enable-static-linking=${{ matrix.static_linking }}
    - name: make
      working-directory: build
      run: make
    - name: make check
      working-directory: build
      run: make check
  
  check-mingw:
    runs-on: windows-latest
    strategy:
      fail-fast: false
      matrix:
        include:
          - msystem: MINGW64
            arch: x86_64
            unicode: true
            static_linking: true
          - msystem: MINGW64
            arch: x86_64
            unicode: true
            static_linking: false
          - msystem: MINGW64
            arch: x86_64
            unicode: false
            static_linking: true
          - msystem: MINGW64
            arch: x86_64
            unicode: false
            static_linking: false
    defaults:
      run:
        shell: msys2 {0}  
    steps:
    - uses: msys2/setup-msys2@v2
      with:
        msystem: ${{ matrix.msystem }}
        release: false  
        update: false
        install: >-
          git
          base-devel
          mingw-w64-${{ matrix.arch }}-toolchain
          mingw-w64-${{ matrix.arch }}-libtool
          mingw-w64-${{ matrix.arch }}-libxml2
          mingw-w64-${{ matrix.arch }}-libxslt
          mingw-w64-${{ matrix.arch }}-openssl
          mingw-w64-${{ matrix.arch }}-gnutls
    - run: git config --global core.autocrlf input
      shell: bash
    - uses: actions/checkout@v2      
    - run: mkdir build
    - name: configur
      working-directory: build
      run: pwd && ../autogen.sh --build="${{ matrix.arch }}-w64-mingw32" --host="${{ matrix.arch }}-w64-mingw32" --enable-unicode=${{ matrix.unicode }} --enable-static-linking=${{ matrix.static_linking }} --enable-mscrypto --enable-mscng 
    - name: make
      working-directory: build
      run: make
    - name: make check
      working-directory: build
      run: make check

  check-msvc:
    runs-on: windows-latest
    env:
      EXTRAS_FOLDER: C:\extras
    steps:
      - name: install dependencies
        run: |
          echo EXTRAS_FOLDER=%EXTRAS_FOLDER%
          echo EXTRAS_URL=%EXTRAS_URL%
          echo EXTRAS_URL=${{ env.EXTRAS_URL }}
          mkdir %EXTRAS_FOLDER%
          dir
          cd %EXTRAS_FOLDER%
          Invoke-WebRequest %EXTRAS_URL%/%LIBXML2_FILE% -O %LIBXML2_FILE%
          dir
          7z x %LIBXML2_FILE%
          dir
        env:
          EXTRAS_URL: https://www.aleksey.com/xmlsec/download/extras
          LIBXML2_FILE: libxml2-2.9.8-noiconv-win-x64.7z
          LIBXSLT_FILE: libxslt-1.1.32-noiconv-win-x64.7z
          OPENSSL_FILE: openssl-1.1.0h-x64.7z
#  - appveyor DownloadFile %EXTRAS_URL%/%LIBXML2_FILE%
#  - 7z x %LIBXML2_FILE%
#  - appveyor DownloadFile %EXTRAS_URL%/%LIBXSLT_FILE%
#  - 7z x %LIBXSLT_FILE%
#  - appveyor DownloadFile %EXTRAS_URL%/%OPENSSL_FILE%
#  - 7z x %OPENSSL_FILE% 
